### PR TITLE
I built a CLI client out of your code

### PR DESCRIPTION
**Pull request by afcady**
I brought in a lot more dependencies to do it -- I'm using Lens and Wreq for HTTP requests and response parsing.  Not sure if you want to go in this direction or not, but either way, thanks a lot for publishing what you did.  It sure was a lot easier to work from your code than having to research the ACME protocol and go from scratch.

### CODE REVIEW

**Comment by afcady** [comment]
Also, regardless of whether you want to use this code, it's probably worth it to merge at least the first commit I made (which just adds *.cabal and stack.yaml).

**Comment by noteed** [comment]
Hi,

I'm really glad you found it useful !

Did you see the branch https://github.com/noteed/acme/tree/script-performs-post-requests ?

I don't have a definitive answer whether I want to merge your code or not. I suggest you host your own version on your GitHub account and that I put a link to it from the top of the README instead (at least until I get a chance to read your code, I'm quite slow to deal with PR...).

**Comment by afcady** [comment]
Yeah, I saw that branch, but I didn't see it until I had already started working with master.  No big deal though because the code that I ended up using seems to be the same in both branches.

BTW, check out how I am using the `post` function to save `Replay-Nonce` values without an extra request.

**Comment by noteed** [comment]
I have mentioned your fork in the README (which will work as a note-to-self too). Thanks.

**Pull request closed without merging**
